# --------------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed
# with this work for additional information regarding copyright
# ownership. The ASF licenses this file to You under the Apache
# License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the
# License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#
# --------------------------------------------------------------------

blank_issues_enabled: true
contact_links:
  - name: ğŸ™ğŸ» Q&A
    url: https://github.com/apache/cloudberry/discussions/categories/q-a
    about: Ask for help when running/developing Apache Cloudberry.
  - name: ğŸ’¡ï¸ New Ideas / Feature Requests
    url: https://github.com/apache/cloudberry/discussions/categories/ideas-feature-requests
    about: Share ideas for new features.
  - name: ğŸ™ï¸ Submit Your Proposal
    url: https://github.com/apache/cloudberry/discussions/categories/proposal
    about: As a developer, proposing any major change or enhancement to Apache Cloudberry.
  - name: ğŸ’¬ï¸ Join Slack for Real-time Chat
    url: https://inviter.co/apache-cloudberry
    about: Real-time chat including QA, Dev, Events and more.
  - name: ğŸª² Issues for Website, Docs
    url: https://github.com/apache/cloudberry-site/issues
    about: Hey, we have one dedicated repo for the website and docs.
